#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_NetStore")]
	public partial class db_NetStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Inserttb_Admin(tb_Admin instance);
    partial void Updatetb_Admin(tb_Admin instance);
    partial void Deletetb_Admin(tb_Admin instance);
    partial void Inserttb_BookInfo(tb_BookInfo instance);
    partial void Updatetb_BookInfo(tb_BookInfo instance);
    partial void Deletetb_BookInfo(tb_BookInfo instance);
    partial void Inserttb_Class(tb_Class instance);
    partial void Updatetb_Class(tb_Class instance);
    partial void Deletetb_Class(tb_Class instance);
    partial void Inserttb_Detail(tb_Detail instance);
    partial void Updatetb_Detail(tb_Detail instance);
    partial void Deletetb_Detail(tb_Detail instance);
    partial void Inserttb_Image(tb_Image instance);
    partial void Updatetb_Image(tb_Image instance);
    partial void Deletetb_Image(tb_Image instance);
    partial void Inserttb_LeaveWord(tb_LeaveWord instance);
    partial void Updatetb_LeaveWord(tb_LeaveWord instance);
    partial void Deletetb_LeaveWord(tb_LeaveWord instance);
    partial void Inserttb_Member(tb_Member instance);
    partial void Updatetb_Member(tb_Member instance);
    partial void Deletetb_Member(tb_Member instance);
    partial void Inserttb_OrderInfo(tb_OrderInfo instance);
    partial void Updatetb_OrderInfo(tb_OrderInfo instance);
    partial void Deletetb_OrderInfo(tb_OrderInfo instance);
    partial void Inserttb_Reply(tb_Reply instance);
    partial void Updatetb_Reply(tb_Reply instance);
    partial void Deletetb_Reply(tb_Reply instance);
    #endregion
		
		public db_NetStoreDataContext() : 
				base(global::DAL.Properties.Settings.Default.db_NetStoreConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public db_NetStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_NetStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_NetStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_NetStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_Admin> tb_Admin
		{
			get
			{
				return this.GetTable<tb_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tb_BookInfo> tb_BookInfo
		{
			get
			{
				return this.GetTable<tb_BookInfo>();
			}
		}
		
		public System.Data.Linq.Table<tb_Class> tb_Class
		{
			get
			{
				return this.GetTable<tb_Class>();
			}
		}
		
		public System.Data.Linq.Table<tb_Detail> tb_Detail
		{
			get
			{
				return this.GetTable<tb_Detail>();
			}
		}
		
		public System.Data.Linq.Table<tb_Image> tb_Image
		{
			get
			{
				return this.GetTable<tb_Image>();
			}
		}
		
		public System.Data.Linq.Table<tb_LeaveWord> tb_LeaveWord
		{
			get
			{
				return this.GetTable<tb_LeaveWord>();
			}
		}
		
		public System.Data.Linq.Table<tb_Member> tb_Member
		{
			get
			{
				return this.GetTable<tb_Member>();
			}
		}
		
		public System.Data.Linq.Table<tb_OrderInfo> tb_OrderInfo
		{
			get
			{
				return this.GetTable<tb_OrderInfo>();
			}
		}
		
		public System.Data.Linq.Table<tb_Reply> tb_Reply
		{
			get
			{
				return this.GetTable<tb_Reply>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Admin")]
	public partial class tb_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminID;
		
		private string _AdminName;
		
		private string _Password;
		
		private string _RealName;
		
		private string _Email;
		
		private System.DateTime _LoadDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnAdminNameChanging(string value);
    partial void OnAdminNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoadDateChanging(System.DateTime value);
    partial void OnLoadDateChanged();
    #endregion
		
		public tb_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this.OnAdminNameChanging(value);
					this.SendPropertyChanging();
					this._AdminName = value;
					this.SendPropertyChanged("AdminName");
					this.OnAdminNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadDate", DbType="DateTime NOT NULL")]
		public System.DateTime LoadDate
		{
			get
			{
				return this._LoadDate;
			}
			set
			{
				if ((this._LoadDate != value))
				{
					this.OnLoadDateChanging(value);
					this.SendPropertyChanging();
					this._LoadDate = value;
					this.SendPropertyChanged("LoadDate");
					this.OnLoadDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BookInfo")]
	public partial class tb_BookInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BookID;
		
		private int _ClassID;
		
		private string _BookName;
		
		private string _BookIntroduce;
		
		private string _Author;
		
		private string _Company;
		
		private string _BookUrl;
		
		private double _MarketPrice;
		
		private double _HotPrice;
		
		private bool _Isrefinement;
		
		private bool _IsHot;
		
		private bool _IsDiscount;
		
		private System.DateTime _LoadDate;
		
		private EntitySet<tb_Detail> _tb_Detail;
		
		private EntityRef<tb_Class> _tb_Class;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnBookNameChanging(string value);
    partial void OnBookNameChanged();
    partial void OnBookIntroduceChanging(string value);
    partial void OnBookIntroduceChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnBookUrlChanging(string value);
    partial void OnBookUrlChanged();
    partial void OnMarketPriceChanging(double value);
    partial void OnMarketPriceChanged();
    partial void OnHotPriceChanging(double value);
    partial void OnHotPriceChanged();
    partial void OnIsrefinementChanging(bool value);
    partial void OnIsrefinementChanged();
    partial void OnIsHotChanging(bool value);
    partial void OnIsHotChanged();
    partial void OnIsDiscountChanging(bool value);
    partial void OnIsDiscountChanged();
    partial void OnLoadDateChanging(System.DateTime value);
    partial void OnLoadDateChanged();
    #endregion
		
		public tb_BookInfo()
		{
			this._tb_Detail = new EntitySet<tb_Detail>(new Action<tb_Detail>(this.attach_tb_Detail), new Action<tb_Detail>(this.detach_tb_Detail));
			this._tb_Class = default(EntityRef<tb_Class>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					if (this._tb_Class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this.OnBookNameChanging(value);
					this.SendPropertyChanging();
					this._BookName = value;
					this.SendPropertyChanged("BookName");
					this.OnBookNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIntroduce", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BookIntroduce
		{
			get
			{
				return this._BookIntroduce;
			}
			set
			{
				if ((this._BookIntroduce != value))
				{
					this.OnBookIntroduceChanging(value);
					this.SendPropertyChanging();
					this._BookIntroduce = value;
					this.SendPropertyChanged("BookIntroduce");
					this.OnBookIntroduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookUrl", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string BookUrl
		{
			get
			{
				return this._BookUrl;
			}
			set
			{
				if ((this._BookUrl != value))
				{
					this.OnBookUrlChanging(value);
					this.SendPropertyChanging();
					this._BookUrl = value;
					this.SendPropertyChanged("BookUrl");
					this.OnBookUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Float NOT NULL")]
		public double MarketPrice
		{
			get
			{
				return this._MarketPrice;
			}
			set
			{
				if ((this._MarketPrice != value))
				{
					this.OnMarketPriceChanging(value);
					this.SendPropertyChanging();
					this._MarketPrice = value;
					this.SendPropertyChanged("MarketPrice");
					this.OnMarketPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotPrice", DbType="Float NOT NULL")]
		public double HotPrice
		{
			get
			{
				return this._HotPrice;
			}
			set
			{
				if ((this._HotPrice != value))
				{
					this.OnHotPriceChanging(value);
					this.SendPropertyChanging();
					this._HotPrice = value;
					this.SendPropertyChanged("HotPrice");
					this.OnHotPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isrefinement", DbType="Bit NOT NULL")]
		public bool Isrefinement
		{
			get
			{
				return this._Isrefinement;
			}
			set
			{
				if ((this._Isrefinement != value))
				{
					this.OnIsrefinementChanging(value);
					this.SendPropertyChanging();
					this._Isrefinement = value;
					this.SendPropertyChanged("Isrefinement");
					this.OnIsrefinementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHot", DbType="Bit NOT NULL")]
		public bool IsHot
		{
			get
			{
				return this._IsHot;
			}
			set
			{
				if ((this._IsHot != value))
				{
					this.OnIsHotChanging(value);
					this.SendPropertyChanging();
					this._IsHot = value;
					this.SendPropertyChanged("IsHot");
					this.OnIsHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDiscount", DbType="Bit NOT NULL")]
		public bool IsDiscount
		{
			get
			{
				return this._IsDiscount;
			}
			set
			{
				if ((this._IsDiscount != value))
				{
					this.OnIsDiscountChanging(value);
					this.SendPropertyChanging();
					this._IsDiscount = value;
					this.SendPropertyChanged("IsDiscount");
					this.OnIsDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadDate", DbType="DateTime NOT NULL")]
		public System.DateTime LoadDate
		{
			get
			{
				return this._LoadDate;
			}
			set
			{
				if ((this._LoadDate != value))
				{
					this.OnLoadDateChanging(value);
					this.SendPropertyChanging();
					this._LoadDate = value;
					this.SendPropertyChanged("LoadDate");
					this.OnLoadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BookInfo_tb_Detail", Storage="_tb_Detail", ThisKey="BookID", OtherKey="BookID")]
		public EntitySet<tb_Detail> tb_Detail
		{
			get
			{
				return this._tb_Detail;
			}
			set
			{
				this._tb_Detail.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Class_tb_BookInfo", Storage="_tb_Class", ThisKey="ClassID", OtherKey="ClassID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tb_Class tb_Class
		{
			get
			{
				return this._tb_Class.Entity;
			}
			set
			{
				tb_Class previousValue = this._tb_Class.Entity;
				if (((previousValue != value) 
							|| (this._tb_Class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Class.Entity = null;
						previousValue.tb_BookInfo.Remove(this);
					}
					this._tb_Class.Entity = value;
					if ((value != null))
					{
						value.tb_BookInfo.Add(this);
						this._ClassID = value.ClassID;
					}
					else
					{
						this._ClassID = default(int);
					}
					this.SendPropertyChanged("tb_Class");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Detail(tb_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_BookInfo = this;
		}
		
		private void detach_tb_Detail(tb_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_BookInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Class")]
	public partial class tb_Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClassID;
		
		private string _ClassName;
		
		private string _CategoryUrl;
		
		private EntitySet<tb_BookInfo> _tb_BookInfo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnCategoryUrlChanging(string value);
    partial void OnCategoryUrlChanged();
    #endregion
		
		public tb_Class()
		{
			this._tb_BookInfo = new EntitySet<tb_BookInfo>(new Action<tb_BookInfo>(this.attach_tb_BookInfo), new Action<tb_BookInfo>(this.detach_tb_BookInfo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryUrl", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CategoryUrl
		{
			get
			{
				return this._CategoryUrl;
			}
			set
			{
				if ((this._CategoryUrl != value))
				{
					this.OnCategoryUrlChanging(value);
					this.SendPropertyChanging();
					this._CategoryUrl = value;
					this.SendPropertyChanged("CategoryUrl");
					this.OnCategoryUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Class_tb_BookInfo", Storage="_tb_BookInfo", ThisKey="ClassID", OtherKey="ClassID")]
		public EntitySet<tb_BookInfo> tb_BookInfo
		{
			get
			{
				return this._tb_BookInfo;
			}
			set
			{
				this._tb_BookInfo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_BookInfo(tb_BookInfo entity)
		{
			this.SendPropertyChanging();
			entity.tb_Class = this;
		}
		
		private void detach_tb_BookInfo(tb_BookInfo entity)
		{
			this.SendPropertyChanging();
			entity.tb_Class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Detail")]
	public partial class tb_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailID;
		
		private int _BookID;
		
		private int _Num;
		
		private int _OrderID;
		
		private double _TotailPrice;
		
		private string _Remark;
		
		private EntityRef<tb_BookInfo> _tb_BookInfo;
		
		private EntityRef<tb_OrderInfo> _tb_OrderInfo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailIDChanging(int value);
    partial void OnDetailIDChanged();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnNumChanging(int value);
    partial void OnNumChanged();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnTotailPriceChanging(double value);
    partial void OnTotailPriceChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public tb_Detail()
		{
			this._tb_BookInfo = default(EntityRef<tb_BookInfo>);
			this._tb_OrderInfo = default(EntityRef<tb_OrderInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetailID
		{
			get
			{
				return this._DetailID;
			}
			set
			{
				if ((this._DetailID != value))
				{
					this.OnDetailIDChanging(value);
					this.SendPropertyChanging();
					this._DetailID = value;
					this.SendPropertyChanged("DetailID");
					this.OnDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="Int NOT NULL")]
		public int BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					if (this._tb_BookInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="Int NOT NULL")]
		public int Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					if (this._tb_OrderInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotailPrice", DbType="Float NOT NULL")]
		public double TotailPrice
		{
			get
			{
				return this._TotailPrice;
			}
			set
			{
				if ((this._TotailPrice != value))
				{
					this.OnTotailPriceChanging(value);
					this.SendPropertyChanging();
					this._TotailPrice = value;
					this.SendPropertyChanged("TotailPrice");
					this.OnTotailPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(200)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BookInfo_tb_Detail", Storage="_tb_BookInfo", ThisKey="BookID", OtherKey="BookID", IsForeignKey=true)]
		public tb_BookInfo tb_BookInfo
		{
			get
			{
				return this._tb_BookInfo.Entity;
			}
			set
			{
				tb_BookInfo previousValue = this._tb_BookInfo.Entity;
				if (((previousValue != value) 
							|| (this._tb_BookInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_BookInfo.Entity = null;
						previousValue.tb_Detail.Remove(this);
					}
					this._tb_BookInfo.Entity = value;
					if ((value != null))
					{
						value.tb_Detail.Add(this);
						this._BookID = value.BookID;
					}
					else
					{
						this._BookID = default(int);
					}
					this.SendPropertyChanged("tb_BookInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_OrderInfo_tb_Detail", Storage="_tb_OrderInfo", ThisKey="OrderID", OtherKey="OrderID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tb_OrderInfo tb_OrderInfo
		{
			get
			{
				return this._tb_OrderInfo.Entity;
			}
			set
			{
				tb_OrderInfo previousValue = this._tb_OrderInfo.Entity;
				if (((previousValue != value) 
							|| (this._tb_OrderInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_OrderInfo.Entity = null;
						previousValue.tb_Detail.Remove(this);
					}
					this._tb_OrderInfo.Entity = value;
					if ((value != null))
					{
						value.tb_Detail.Add(this);
						this._OrderID = value.OrderID;
					}
					else
					{
						this._OrderID = default(int);
					}
					this.SendPropertyChanged("tb_OrderInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Image")]
	public partial class tb_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ImageID;
		
		private string _ImageName;
		
		private string _ImageUrl;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnImageIDChanging(int value);
    partial void OnImageIDChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    partial void OnImageUrlChanging(string value);
    partial void OnImageUrlChanged();
    #endregion
		
		public tb_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageUrl", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if ((this._ImageUrl != value))
				{
					this.OnImageUrlChanging(value);
					this.SendPropertyChanging();
					this._ImageUrl = value;
					this.SendPropertyChanged("ImageUrl");
					this.OnImageUrlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_LeaveWord")]
	public partial class tb_LeaveWord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Uid;
		
		private string _Subject;
		
		private string _Content;
		
		private System.DateTime _DateTime;
		
		private string _IP;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUidChanging(string value);
    partial void OnUidChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    #endregion
		
		public tb_LeaveWord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Uid
		{
			get
			{
				return this._Uid;
			}
			set
			{
				if ((this._Uid != value))
				{
					this.OnUidChanging(value);
					this.SendPropertyChanging();
					this._Uid = value;
					this.SendPropertyChanged("Uid");
					this.OnUidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Member")]
	public partial class tb_Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemberID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _RealName;
		
		private bool _Sex;
		
		private string _Phonecode;
		
		private string _Email;
		
		private string _Address;
		
		private string _PostCode;
		
		private System.DateTime _LoadDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIDChanging(int value);
    partial void OnMemberIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnSexChanging(bool value);
    partial void OnSexChanged();
    partial void OnPhonecodeChanging(string value);
    partial void OnPhonecodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPostCodeChanging(string value);
    partial void OnPostCodeChanged();
    partial void OnLoadDateChanging(System.DateTime value);
    partial void OnLoadDateChanged();
    #endregion
		
		public tb_Member()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemberID
		{
			get
			{
				return this._MemberID;
			}
			set
			{
				if ((this._MemberID != value))
				{
					this.OnMemberIDChanging(value);
					this.SendPropertyChanging();
					this._MemberID = value;
					this.SendPropertyChanged("MemberID");
					this.OnMemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Bit NOT NULL")]
		public bool Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phonecode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Phonecode
		{
			get
			{
				return this._Phonecode;
			}
			set
			{
				if ((this._Phonecode != value))
				{
					this.OnPhonecodeChanging(value);
					this.SendPropertyChanging();
					this._Phonecode = value;
					this.SendPropertyChanged("Phonecode");
					this.OnPhonecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this.OnPostCodeChanging(value);
					this.SendPropertyChanging();
					this._PostCode = value;
					this.SendPropertyChanged("PostCode");
					this.OnPostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadDate", DbType="DateTime NOT NULL")]
		public System.DateTime LoadDate
		{
			get
			{
				return this._LoadDate;
			}
			set
			{
				if ((this._LoadDate != value))
				{
					this.OnLoadDateChanging(value);
					this.SendPropertyChanging();
					this._LoadDate = value;
					this.SendPropertyChanged("LoadDate");
					this.OnLoadDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_OrderInfo")]
	public partial class tb_OrderInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderID;
		
		private System.DateTime _OrderDate;
		
		private double _BooksFee;
		
		private double _ShipFee;
		
		private double _TotalPrice;
		
		private string _ShipType;
		
		private string _ReceiverName;
		
		private string _ReceiverPhone;
		
		private string _ReceiverPostCode;
		
		private string _ReceiverAddress;
		
		private string _ReceiverEmail;
		
		private bool _IsConfirm;
		
		private bool _IsSend;
		
		private bool _IsEnd;
		
		private System.Nullable<int> _AdminID;
		
		private System.Nullable<System.DateTime> _ConfirmTime;
		
		private EntitySet<tb_Detail> _tb_Detail;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnOrderDateChanging(System.DateTime value);
    partial void OnOrderDateChanged();
    partial void OnBooksFeeChanging(double value);
    partial void OnBooksFeeChanged();
    partial void OnShipFeeChanging(double value);
    partial void OnShipFeeChanged();
    partial void OnTotalPriceChanging(double value);
    partial void OnTotalPriceChanged();
    partial void OnShipTypeChanging(string value);
    partial void OnShipTypeChanged();
    partial void OnReceiverNameChanging(string value);
    partial void OnReceiverNameChanged();
    partial void OnReceiverPhoneChanging(string value);
    partial void OnReceiverPhoneChanged();
    partial void OnReceiverPostCodeChanging(string value);
    partial void OnReceiverPostCodeChanged();
    partial void OnReceiverAddressChanging(string value);
    partial void OnReceiverAddressChanged();
    partial void OnReceiverEmailChanging(string value);
    partial void OnReceiverEmailChanged();
    partial void OnIsConfirmChanging(bool value);
    partial void OnIsConfirmChanged();
    partial void OnIsSendChanging(bool value);
    partial void OnIsSendChanged();
    partial void OnIsEndChanging(bool value);
    partial void OnIsEndChanged();
    partial void OnAdminIDChanging(System.Nullable<int> value);
    partial void OnAdminIDChanged();
    partial void OnConfirmTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnConfirmTimeChanged();
    #endregion
		
		public tb_OrderInfo()
		{
			this._tb_Detail = new EntitySet<tb_Detail>(new Action<tb_Detail>(this.attach_tb_Detail), new Action<tb_Detail>(this.detach_tb_Detail));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime NOT NULL")]
		public System.DateTime OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				if ((this._OrderDate != value))
				{
					this.OnOrderDateChanging(value);
					this.SendPropertyChanging();
					this._OrderDate = value;
					this.SendPropertyChanged("OrderDate");
					this.OnOrderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BooksFee", DbType="Float NOT NULL")]
		public double BooksFee
		{
			get
			{
				return this._BooksFee;
			}
			set
			{
				if ((this._BooksFee != value))
				{
					this.OnBooksFeeChanging(value);
					this.SendPropertyChanging();
					this._BooksFee = value;
					this.SendPropertyChanged("BooksFee");
					this.OnBooksFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipFee", DbType="Float NOT NULL")]
		public double ShipFee
		{
			get
			{
				return this._ShipFee;
			}
			set
			{
				if ((this._ShipFee != value))
				{
					this.OnShipFeeChanging(value);
					this.SendPropertyChanging();
					this._ShipFee = value;
					this.SendPropertyChanged("ShipFee");
					this.OnShipFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Float NOT NULL")]
		public double TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ShipType
		{
			get
			{
				return this._ShipType;
			}
			set
			{
				if ((this._ShipType != value))
				{
					this.OnShipTypeChanging(value);
					this.SendPropertyChanging();
					this._ShipType = value;
					this.SendPropertyChanged("ShipType");
					this.OnShipTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceiverName
		{
			get
			{
				return this._ReceiverName;
			}
			set
			{
				if ((this._ReceiverName != value))
				{
					this.OnReceiverNameChanging(value);
					this.SendPropertyChanging();
					this._ReceiverName = value;
					this.SendPropertyChanged("ReceiverName");
					this.OnReceiverNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverPhone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ReceiverPhone
		{
			get
			{
				return this._ReceiverPhone;
			}
			set
			{
				if ((this._ReceiverPhone != value))
				{
					this.OnReceiverPhoneChanging(value);
					this.SendPropertyChanging();
					this._ReceiverPhone = value;
					this.SendPropertyChanged("ReceiverPhone");
					this.OnReceiverPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverPostCode", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ReceiverPostCode
		{
			get
			{
				return this._ReceiverPostCode;
			}
			set
			{
				if ((this._ReceiverPostCode != value))
				{
					this.OnReceiverPostCodeChanging(value);
					this.SendPropertyChanging();
					this._ReceiverPostCode = value;
					this.SendPropertyChanged("ReceiverPostCode");
					this.OnReceiverPostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverAddress", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReceiverAddress
		{
			get
			{
				return this._ReceiverAddress;
			}
			set
			{
				if ((this._ReceiverAddress != value))
				{
					this.OnReceiverAddressChanging(value);
					this.SendPropertyChanging();
					this._ReceiverAddress = value;
					this.SendPropertyChanged("ReceiverAddress");
					this.OnReceiverAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceiverEmail
		{
			get
			{
				return this._ReceiverEmail;
			}
			set
			{
				if ((this._ReceiverEmail != value))
				{
					this.OnReceiverEmailChanging(value);
					this.SendPropertyChanging();
					this._ReceiverEmail = value;
					this.SendPropertyChanged("ReceiverEmail");
					this.OnReceiverEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsConfirm", DbType="Bit NOT NULL")]
		public bool IsConfirm
		{
			get
			{
				return this._IsConfirm;
			}
			set
			{
				if ((this._IsConfirm != value))
				{
					this.OnIsConfirmChanging(value);
					this.SendPropertyChanging();
					this._IsConfirm = value;
					this.SendPropertyChanged("IsConfirm");
					this.OnIsConfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSend", DbType="Bit NOT NULL")]
		public bool IsSend
		{
			get
			{
				return this._IsSend;
			}
			set
			{
				if ((this._IsSend != value))
				{
					this.OnIsSendChanging(value);
					this.SendPropertyChanging();
					this._IsSend = value;
					this.SendPropertyChanged("IsSend");
					this.OnIsSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnd", DbType="Bit NOT NULL")]
		public bool IsEnd
		{
			get
			{
				return this._IsEnd;
			}
			set
			{
				if ((this._IsEnd != value))
				{
					this.OnIsEndChanging(value);
					this.SendPropertyChanging();
					this._IsEnd = value;
					this.SendPropertyChanged("IsEnd");
					this.OnIsEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="Int")]
		public System.Nullable<int> AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConfirmTime
		{
			get
			{
				return this._ConfirmTime;
			}
			set
			{
				if ((this._ConfirmTime != value))
				{
					this.OnConfirmTimeChanging(value);
					this.SendPropertyChanging();
					this._ConfirmTime = value;
					this.SendPropertyChanged("ConfirmTime");
					this.OnConfirmTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_OrderInfo_tb_Detail", Storage="_tb_Detail", ThisKey="OrderID", OtherKey="OrderID")]
		public EntitySet<tb_Detail> tb_Detail
		{
			get
			{
				return this._tb_Detail;
			}
			set
			{
				this._tb_Detail.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Detail(tb_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_OrderInfo = this;
		}
		
		private void detach_tb_Detail(tb_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_OrderInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Reply")]
	public partial class tb_Reply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UName;
		
		private string _Content;
		
		private System.Nullable<System.DateTime> _DateTime;
		
		private System.Nullable<int> _ReplyID;
		
		private string _IP;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUNameChanging(string value);
    partial void OnUNameChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeChanged();
    partial void OnReplyIDChanging(System.Nullable<int> value);
    partial void OnReplyIDChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    #endregion
		
		public tb_Reply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UName", DbType="NVarChar(50)")]
		public string UName
		{
			get
			{
				return this._UName;
			}
			set
			{
				if ((this._UName != value))
				{
					this.OnUNameChanging(value);
					this.SendPropertyChanging();
					this._UName = value;
					this.SendPropertyChanged("UName");
					this.OnUNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyID", DbType="Int")]
		public System.Nullable<int> ReplyID
		{
			get
			{
				return this._ReplyID;
			}
			set
			{
				if ((this._ReplyID != value))
				{
					this.OnReplyIDChanging(value);
					this.SendPropertyChanging();
					this._ReplyID = value;
					this.SendPropertyChanged("ReplyID");
					this.OnReplyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="NVarChar(20)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
